import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import Intro from '../components/Intro/Intro'
import Projects, { Store } from '../components/Projects/Projects'

export default function Home() {
  return (
    <Box mt={['170px', '170px', '70px']}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <Intro />
        <Projects />
      </main>
    </Box>
  )
}
